import { useEffect, useMemo, useState, type FormEvent } from "react";
import { getCatalog,getDelivery,getOrders,isSignedIn,logout,saveCatalog,saveDelivery,signIn,updateOrderStatus,type Delivery,type DeliveryRate,type Order,type Product } from "./firebase-rest";
import { compressImage } from "./image-file";
import { wilayas } from "./wilayas";

const money=(value:number)=>new Intl.NumberFormat("fr-DZ").format(value||0)+" DA";
const imageUrl=(image:string)=>image.startsWith("data:")||/^https?:/.test(image)?image:`../cosmetique/${image.replace(/^\//,"")}`;
const statusLabels:Record<string,string>={new:"Nouvelle",confirmed:"Confirmée",delivered:"Livrée",cancelled:"Annulée"};
const slug=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");

export default function App(){
 const [signed,setSigned]=useState(isSignedIn());
 if(!signed)return <Login onLogin={()=>setSigned(true)}/>;
 return <Dashboard onLogout={()=>{logout();setSigned(false)}}/>;
}

function Login({onLogin}:{onLogin:()=>void}){
 const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError("");const data=new FormData(e.currentTarget);try{await signIn(String(data.get("email")),String(data.get("password")));onLogin()}catch(err){setError(err instanceof Error?err.message:"Connexion impossible.")}finally{setBusy(false)}};
 return <main className="loginPage"><section className="loginCard"><div className="brand"><span>DERMA<i>É</i></span><small>×</small><span>PRO <i>LENS</i></span></div><p className="eyebrow">ESPACE PRIVÉ</p><h1>Administration</h1><p>Commandes, catalogue et livraison réunis dans un seul espace.</p><form onSubmit={submit}><label>Adresse e-mail<input name="email" type="email" required autoComplete="username"/></label><label>Mot de passe<input name="password" type="password" required autoComplete="current-password"/></label>{error&&<p className="error">{error}</p>}<button disabled={busy}>{busy?"Connexion…":"Se connecter"}</button></form><small>Accès réservé à l’administrateur.</small></section></main>
}

function Dashboard({onLogout}:{onLogout:()=>void}){
 const [tab,setTab]=useState<"orders"|"catalog"|"delivery">("orders");const [orders,setOrders]=useState<Order[]>([]);const [products,setProducts]=useState<Product[]>([]);const [delivery,setDelivery]=useState<Delivery>({desk:450,home:700,wilayas:{}});const [loading,setLoading]=useState(true);const [notice,setNotice]=useState("");
 const refresh=async()=>{setLoading(true);setNotice("");try{const[o,p,d]=await Promise.all([getOrders(),getCatalog(),getDelivery()]);setOrders(o);setProducts(p);setDelivery(d)}catch(err){setNotice(err instanceof Error?err.message:"Chargement impossible.")}finally{setLoading(false)}};
 useEffect(()=>{refresh()},[]);
 const stats={new:orders.filter(o=>o.status==="new").length,cosmetics:orders.filter(o=>o.source==="cosmetics").length,lens:orders.filter(o=>o.source==="lens").length};
 return <div className="shell"><aside><div className="brand solo">DERMA<i>É</i><small>ADMIN</small></div><nav><button className={tab==="orders"?"active":""} onClick={()=>setTab("orders")}><span>▦</span>Commandes{stats.new>0&&<b>{stats.new}</b>}</button><button className={tab==="catalog"?"active":""} onClick={()=>setTab("catalog")}><span>◇</span>Catalogue</button><button className={tab==="delivery"?"active":""} onClick={()=>setTab("delivery")}><span>⌁</span>Livraison</button></nav><button className="logout" onClick={onLogout}>Se déconnecter</button></aside><main className="dashboard"><header><div><p className="eyebrow">TABLEAU DE BORD</p><h1>{tab==="orders"?"Commandes":tab==="catalog"?"Catalogue cosmétique":"Livraison par wilaya"}</h1></div><button className="refresh" onClick={refresh} disabled={loading}>{loading?"Chargement…":"↻ Actualiser"}</button></header>{notice&&<p className="notice">{notice}</p>}{tab==="orders"&&<><section className="stats"><article><small>NOUVELLES</small><strong>{stats.new}</strong></article><article><small>COSMÉTIQUE</small><strong>{stats.cosmetics}</strong></article><article><small>PRO LENS</small><strong>{stats.lens}</strong></article><article><small>PRODUITS</small><strong>{products.length}</strong></article></section><Orders orders={orders} onUpdate={async(id,status)=>{await updateOrderStatus(id,status);setOrders(list=>list.map(o=>o.id===id?{...o,status}:o))}}/></>}{tab==="catalog"&&<Catalog products={products} onChange={async next=>{await saveCatalog(next);setProducts(next);setNotice("Catalogue enregistré avec succès.")}}/>}{tab==="delivery"&&<DeliveryPanel delivery={delivery} onSave={async next=>{await saveDelivery(next);setDelivery(next);setNotice("Tarifs des 58 wilayas enregistrés.")}}/>}</main></div>
}

function Orders({orders,onUpdate}:{orders:Order[];onUpdate:(id:string,status:string)=>Promise<void>}){
 const [filter,setFilter]=useState("all");const visible=useMemo(()=>orders.filter(o=>filter==="all"||o.source===filter||o.status===filter),[orders,filter]);
 return <section className="panel"><div className="panelHead"><div className="filters">{[["all","Toutes"],["new","Nouvelles"],["cosmetics","Cosmétique"],["lens","Pro Lens"]].map(([key,label])=><button key={key} className={filter===key?"active":""} onClick={()=>setFilter(key)}>{label}</button>)}</div><small>100 dernières commandes maximum</small></div><div className="orders">{visible.length===0?<div className="empty">Aucune commande dans cette vue.</div>:visible.map(order=><article className="order" key={order.id}><div className="orderTop"><span className={`source ${order.source}`}>{order.source==="lens"?"PRO LENS":"DERMAÉ"}</span><span className={`status ${order.status}`}>{statusLabels[order.status]||order.status}</span><time>{order.createdAt?new Date(order.createdAt).toLocaleString("fr-DZ"):""}</time></div><div className="orderGrid"><div><small>CLIENT</small><strong>{order.customerName}</strong><a href={`tel:${order.phone}`}>{order.phone}</a><span>{order.wilaya}</span><span>{order.address}</span></div><div><small>PRODUIT</small><strong>{order.productName}</strong><span>{order.productBrand}</span><span>{order.quantity} × {money(order.unitPrice)}</span>{order.delivery&&<span>{order.delivery==="desk"?"Stop Desk":"Domicile"} · {money(order.shipping||0)}</span>}{order.prescriptionPhoto&&<a className="prescriptionLink" href={order.prescriptionPhoto} target="_blank" rel="noreferrer"><img src={order.prescriptionPhoto} alt="Ordonnance"/><span>Voir l’ordonnance</span></a>}</div><div className="orderTotal"><small>TOTAL</small><strong>{money(order.total)}</strong></div></div><div className="actions"><button onClick={()=>onUpdate(order.id,"confirmed")}>Confirmer</button><button onClick={()=>onUpdate(order.id,"delivered")}>Livrée</button><button className="danger" onClick={()=>onUpdate(order.id,"cancelled")}>Annuler</button></div></article>)}</div></section>
}

function Catalog({products,onChange}:{products:Product[];onChange:(next:Product[])=>Promise<void>}){
 const [editor,setEditor]=useState<Product|null|"new">(null);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [preview,setPreview]=useState("");
 const editing=editor&&editor!=="new"?editor:null;
 const openNew=()=>{setEditor("new");setPreview("");setError("")};
 const openEdit=(product:Product)=>{setEditor(product);setPreview(imageUrl(product.image));setError("")};
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setSaving(true);setError("");const data=new FormData(e.currentTarget);try{const file=data.get("imageFile");let image=editing?.image||"";if(file instanceof File&&file.size)image=await compressImage(file);if(!image)throw new Error("Choisissez une photo depuis votre appareil.");const name=String(data.get("name"));const product:Product={id:editing?.id||`${slug(name)}-${Date.now().toString().slice(-5)}`,brand:String(data.get("brand")),name,price:Number(data.get("price")),size:String(data.get("size")),image,short:String(data.get("short")),description:String(data.get("description")),benefits:String(data.get("benefits")).split(",").map(v=>v.trim()).filter(Boolean),usage:String(data.get("usage"))};const next=editing?products.map(p=>p.id===editing.id?product:p):[...products,product];await onChange(next);setEditor(null)}catch(err){setError(err instanceof Error?err.message:"Enregistrement impossible.")}finally{setSaving(false)}};
 const remove=async(product:Product)=>{if(!confirm(`Supprimer ${product.name} ?`))return;setSaving(true);try{await onChange(products.filter(p=>p.id!==product.id))}finally{setSaving(false)}};
 return <section className="panel catalogPage"><div className="catalogHeader"><div><p className="eyebrow">CATALOGUE</p><h2>Produits publiés</h2><small>{products.length} références</small></div><button className="addButton" onClick={openNew}>+ Ajouter un nouveau produit</button></div><div className="publishedGrid">{products.map(product=><article key={product.id}><div className="productThumb"><img src={imageUrl(product.image)} alt={product.name}/></div><div><small>{product.brand} · {product.size}</small><strong>{product.name}</strong><span>{money(product.price)}</span></div><div className="productActions"><button onClick={()=>openEdit(product)}>Modifier</button><button className="delete" disabled={saving} onClick={()=>remove(product)}>Supprimer</button></div></article>)}</div>{editor&&<div className="editorBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setEditor(null)}}><section className="productEditor"><div className="editorHead"><div><p className="eyebrow">{editing?"MODIFIER LE PRODUIT":"NOUVEAU PRODUIT"}</p><h2>{editing?editing.name:"Ajouter au catalogue"}</h2></div><button onClick={()=>setEditor(null)} aria-label="Fermer">×</button></div><form key={editing?.id||"new"} onSubmit={submit}><div className="imagePicker"><div className="imagePreview">{preview?<img src={preview} alt="Aperçu"/>:<span>Photo du produit</span>}</div><label>Choisir une photo depuis votre téléphone ou ordinateur<input name="imageFile" type="file" accept="image/*" required={!editing} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{setPreview(await compressImage(file))}catch(err){setError(err instanceof Error?err.message:"Photo invalide.")}}}/></label></div><div className="two"><label>Marque<input name="brand" required defaultValue={editing?.brand}/></label><label>Nom<input name="name" required defaultValue={editing?.name}/></label></div><div className="two"><label>Prix (DA)<input name="price" type="number" min="0" required defaultValue={editing?.price}/></label><label>Format<input name="size" placeholder="30 ml" required defaultValue={editing?.size}/></label></div><label>Résumé<input name="short" required defaultValue={editing?.short}/></label><label>Description<textarea name="description" required defaultValue={editing?.description}/></label><label>Bénéfices séparés par des virgules<input name="benefits" required defaultValue={editing?.benefits.join(", ")}/></label><label>Conseil d’utilisation<textarea name="usage" required defaultValue={editing?.usage}/></label>{error&&<p className="error">{error}</p>}<button disabled={saving}>{saving?"Enregistrement…":editing?"Enregistrer les modifications":"Ajouter le produit"}</button></form></section></div>}</section>
}

function DeliveryPanel({delivery,onSave}:{delivery:Delivery;onSave:(next:Delivery)=>Promise<void>}){
 const build=()=>Object.fromEntries(wilayas.map(w=>[w,delivery.wilayas?.[w]||{desk:delivery.desk,home:delivery.home}])) as Record<string,DeliveryRate>;
 const [rates,setRates]=useState<Record<string,DeliveryRate>>(build);const [saving,setSaving]=useState(false);
 useEffect(()=>{setRates(build())},[delivery]);
 const update=(wilaya:string,key:keyof DeliveryRate,value:number)=>setRates(current=>({...current,[wilaya]:{...current[wilaya],[key]:value}}));
 const submit=async(e:FormEvent)=>{e.preventDefault();setSaving(true);try{await onSave({desk:delivery.desk,home:delivery.home,wilayas:rates})}finally{setSaving(false)}};
 return <section className="panel wilayaDelivery"><div className="deliveryHeader"><div><p className="eyebrow">58 WILAYAS</p><h2>Tarifs Stop Desk et domicile</h2><p>Modifiez directement le tarif de chaque wilaya.</p></div></div><form onSubmit={submit}><div className="wilayaHead"><span>Wilaya</span><span>Stop Desk</span><span>Domicile</span></div><div className="wilayaRates">{wilayas.map(w=><label key={w}><strong>{w}</strong><span><input aria-label={`Stop Desk ${w}`} type="number" min="0" value={rates[w]?.desk??delivery.desk} onChange={e=>update(w,"desk",Number(e.target.value))}/><em>DA</em></span><span><input aria-label={`Domicile ${w}`} type="number" min="0" value={rates[w]?.home??delivery.home} onChange={e=>update(w,"home",Number(e.target.value))}/><em>DA</em></span></label>)}</div><button className="saveDelivery" disabled={saving}>{saving?"Enregistrement…":"Enregistrer les 58 tarifs"}</button></form></section>
}
