import { useEffect, useMemo, useState, type FormEvent } from "react";
import { getCatalog,getDelivery,getOrders,isSignedIn,logout,saveCatalog,saveDelivery,signIn,updateOrderStatus,type Delivery,type Order,type Product } from "./firebase-rest";

const money=(value:number)=>new Intl.NumberFormat("fr-DZ").format(value||0)+" DA";
const imageUrl=(image:string)=>/^https?:/.test(image)?image:`../cosmetique/${image.replace(/^\//,"")}`;
const statusLabels:Record<string,string>={new:"Nouvelle",confirmed:"Confirmée",delivered:"Livrée",cancelled:"Annulée"};

export default function App(){
 const [signed,setSigned]=useState(isSignedIn());
 if(!signed)return <Login onLogin={()=>setSigned(true)}/>;
 return <Dashboard onLogout={()=>{logout();setSigned(false)}}/>;
}

function Login({onLogin}:{onLogin:()=>void}){
 const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError("");const data=new FormData(e.currentTarget);try{await signIn(String(data.get("email")),String(data.get("password")));onLogin()}catch(err){setError(err instanceof Error?err.message:"Connexion impossible.")}finally{setBusy(false)}};
 return <main className="loginPage"><section className="loginCard"><div className="brand"><span>DERMA<i>É</i></span><small>×</small><span>PRO <i>LENS</i></span></div><p className="eyebrow">ESPACE PRIVÉ</p><h1>Administration</h1><p>Commandes, catalogue et livraison réunis dans un seul espace.</p><form onSubmit={submit}><label>Adresse e-mail<input name="email" type="email" required autoComplete="username"/></label><label>Mot de passe<input name="password" type="password" required autoComplete="current-password"/></label>{error&&<p className="error">{error}</p>}<button disabled={busy}>{busy?"Connexion…":"Se connecter"}</button></form><small>Accès réservé à l’administrateur.</small></section></main>
}

function Dashboard({onLogout}:{onLogout:()=>void}){
 const [tab,setTab]=useState<"orders"|"catalog"|"delivery">("orders");const [orders,setOrders]=useState<Order[]>([]);const [products,setProducts]=useState<Product[]>([]);const [delivery,setDelivery]=useState<Delivery>({desk:450,home:700});const [loading,setLoading]=useState(true);const [notice,setNotice]=useState("");
 const refresh=async()=>{setLoading(true);setNotice("");try{const[o,p,d]=await Promise.all([getOrders(),getCatalog(),getDelivery()]);setOrders(o);setProducts(p);setDelivery(d)}catch(err){setNotice(err instanceof Error?err.message:"Chargement impossible.")}finally{setLoading(false)}};
 useEffect(()=>{refresh()},[]);
 const stats={new:orders.filter(o=>o.status==="new").length,cosmetics:orders.filter(o=>o.source==="cosmetics").length,lens:orders.filter(o=>o.source==="lens").length};
 return <div className="shell"><aside><div className="brand solo">DERMA<i>É</i><small>ADMIN</small></div><nav><button className={tab==="orders"?"active":""} onClick={()=>setTab("orders")}><span>▦</span>Commandes{stats.new>0&&<b>{stats.new}</b>}</button><button className={tab==="catalog"?"active":""} onClick={()=>setTab("catalog")}><span>◇</span>Catalogue</button><button className={tab==="delivery"?"active":""} onClick={()=>setTab("delivery")}><span>⌁</span>Livraison</button></nav><div className="quota"><b>Mode économique</b><p>Pas de temps réel. Catalogue mis en cache 1 heure côté boutique.</p></div><button className="logout" onClick={onLogout}>Se déconnecter</button></aside><main className="dashboard"><header><div><p className="eyebrow">TABLEAU DE BORD</p><h1>{tab==="orders"?"Commandes":tab==="catalog"?"Catalogue cosmétique":"Prix de livraison"}</h1></div><button className="refresh" onClick={refresh} disabled={loading}>{loading?"Chargement…":"↻ Actualiser"}</button></header>{notice&&<p className="notice">{notice}</p>}<section className="stats"><article><small>NOUVELLES</small><strong>{stats.new}</strong></article><article><small>COSMÉTIQUE</small><strong>{stats.cosmetics}</strong></article><article><small>PRO LENS</small><strong>{stats.lens}</strong></article><article><small>PRODUITS</small><strong>{products.length}</strong></article></section>{tab==="orders"&&<Orders orders={orders} onUpdate={async(id,status)=>{await updateOrderStatus(id,status);setOrders(list=>list.map(o=>o.id===id?{...o,status}:o))}}/>}{tab==="catalog"&&<Catalog products={products} onChange={async next=>{await saveCatalog(next);setProducts(next);setNotice("Catalogue enregistré. Les boutiques se mettront à jour au prochain rafraîchissement du cache.")}}/>}{tab==="delivery"&&<DeliveryPanel delivery={delivery} onSave={async next=>{await saveDelivery(next);setDelivery(next);setNotice("Prix de livraison enregistrés.")}}/>}</main></div>
}

function Orders({orders,onUpdate}:{orders:Order[];onUpdate:(id:string,status:string)=>Promise<void>}){
 const [filter,setFilter]=useState("all");const visible=useMemo(()=>orders.filter(o=>filter==="all"||o.source===filter||o.status===filter),[orders,filter]);
 return <section className="panel"><div className="panelHead"><div className="filters">{[["all","Toutes"],["new","Nouvelles"],["cosmetics","Cosmétique"],["lens","Pro Lens"]].map(([key,label])=><button key={key} className={filter===key?"active":""} onClick={()=>setFilter(key)}>{label}</button>)}</div><small>100 dernières commandes maximum</small></div><div className="orders">{visible.length===0?<div className="empty">Aucune commande dans cette vue.</div>:visible.map(order=><article className="order" key={order.id}><div className="orderTop"><span className={`source ${order.source}`}>{order.source==="lens"?"PRO LENS":"DERMAÉ"}</span><span className={`status ${order.status}`}>{statusLabels[order.status]||order.status}</span><time>{order.createdAt?new Date(order.createdAt).toLocaleString("fr-DZ"):""}</time></div><div className="orderGrid"><div><small>CLIENT</small><strong>{order.customerName}</strong><a href={`tel:${order.phone}`}>{order.phone}</a><span>{order.wilaya}</span><span>{order.address}</span></div><div><small>PRODUIT</small><strong>{order.productName}</strong><span>{order.productBrand}</span><span>{order.quantity} × {money(order.unitPrice)}</span>{order.delivery&&<span>{order.delivery==="desk"?"Stop Desk":"Domicile"} · {money(order.shipping||0)}</span>}</div><div className="orderTotal"><small>TOTAL</small><strong>{money(order.total)}</strong></div></div><div className="actions"><button onClick={()=>onUpdate(order.id,"confirmed")}>Confirmer</button><button onClick={()=>onUpdate(order.id,"delivered")}>Livrée</button><button className="danger" onClick={()=>onUpdate(order.id,"cancelled")}>Annuler</button></div></article>)}</div></section>
}

function Catalog({products,onChange}:{products:Product[];onChange:(next:Product[])=>Promise<void>}){
 const [saving,setSaving]=useState(false);const [error,setError]=useState("");
 const add=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setSaving(true);setError("");const data=new FormData(e.currentTarget);const product:Product={id:String(data.get("id")||Date.now()),brand:String(data.get("brand")),name:String(data.get("name")),price:Number(data.get("price")),size:String(data.get("size")),image:String(data.get("image")),short:String(data.get("short")),description:String(data.get("description")),benefits:String(data.get("benefits")).split(",").map(v=>v.trim()).filter(Boolean),usage:String(data.get("usage"))};try{await onChange([...products,product]);e.currentTarget.reset()}catch(err){setError(err instanceof Error?err.message:"Enregistrement impossible.")}finally{setSaving(false)}};
 const remove=async(product:Product)=>{if(!confirm(`Supprimer ${product.name} ?`))return;setSaving(true);try{await onChange(products.filter(p=>p.id!==product.id))}finally{setSaving(false)}};
 return <div className="catalogLayout"><section className="panel addProduct"><p className="eyebrow">NOUVEAU PRODUIT</p><h2>Ajouter au catalogue</h2><form onSubmit={add}><div className="two"><label>Marque<input name="brand" required/></label><label>Nom<input name="name" required/></label></div><div className="three"><label>Prix (DA)<input name="price" type="number" min="0" required/></label><label>Format<input name="size" placeholder="30 ml" required/></label><label>Identifiant<input name="id" placeholder="auto si vide"/></label></div><label>URL de la photo<input name="image" required placeholder="https://…"/></label><label>Résumé<input name="short" required/></label><label>Description<textarea name="description" required/></label><label>Bénéfices séparés par des virgules<input name="benefits" required/></label><label>Conseil d’utilisation<textarea name="usage" required/></label>{error&&<p className="error">{error}</p>}<button disabled={saving}>{saving?"Enregistrement…":"Ajouter le produit"}</button></form></section><section className="panel catalogList"><div className="panelHead"><h2>Produits publiés</h2><small>{products.length} références · 1 seule lecture Firebase</small></div>{products.map(product=><article key={product.id}><div className="productThumb"><img src={imageUrl(product.image)} alt=""/></div><div><small>{product.brand} · {product.size}</small><strong>{product.name}</strong><span>{money(product.price)}</span></div><button className="delete" disabled={saving} onClick={()=>remove(product)}>Supprimer</button></article>)}</section></div>
}

function DeliveryPanel({delivery,onSave}:{delivery:Delivery;onSave:(next:Delivery)=>Promise<void>}){
 const [saving,setSaving]=useState(false);const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setSaving(true);const data=new FormData(e.currentTarget);try{await onSave({desk:Number(data.get("desk")),home:Number(data.get("home"))})}finally{setSaving(false)}};
 return <section className="panel deliveryPanel"><div><p className="eyebrow">DERMAÉ</p><h2>Tarifs affichés dans le formulaire cosmétique</h2><p>Ces prix sont chargés une fois puis conservés une heure dans le navigateur des visiteurs pour limiter les lectures Firestore.</p></div><form onSubmit={submit}><label><span><b>Stop Desk</b><small>Livraison au bureau</small></span><input name="desk" type="number" min="0" defaultValue={delivery.desk} key={`desk-${delivery.desk}`}/><em>DA</em></label><label><span><b>Domicile</b><small>Livraison à l’adresse du client</small></span><input name="home" type="number" min="0" defaultValue={delivery.home} key={`home-${delivery.home}`}/><em>DA</em></label><button disabled={saving}>{saving?"Enregistrement…":"Enregistrer les tarifs"}</button></form></section>
}
