import { useMemo, useState } from "react";

type Product = { id: string; brand: string; name: string; price: number; type: string; image: string; description: string; boxes: string };
const products: Product[] = [
  { id:"air-optix", brand:"ALCON", name:"Air Optix plus HydraGlyde", price:3900, type:"Mensuelles", boxes:"6 lentilles", image:"https://d17sjz7j5l4n5m.cloudfront.net/prescriptions/8acbb40980531e416ed5ba69b7ce2e2f", description:"Lentilles mensuelles respirantes, conçues pour un confort net du matin au soir." },
  { id:"biofinity", brand:"COOPERVISION", name:"Biofinity", price:4200, type:"Mensuelles", boxes:"6 lentilles", image:"https://d17sjz7j5l4n5m.cloudfront.net/prescriptions/12b52d43ffacf825a9d2c27be0c80c4b", description:"Une vision précise et un excellent maintien de l’hydratation, jour après jour." },
  { id:"soflens", brand:"BAUSCH + LOMB", name:"SofLens 59", price:2900, type:"Mensuelles", boxes:"6 lentilles", image:"https://d17sjz7j5l4n5m.cloudfront.net/products/50555caa86d98edefcc2758b9c6dcd53", description:"Une solution fiable et confortable pour votre routine de port mensuel." },
  { id:"ultra", brand:"BAUSCH + LOMB", name:"Ultra", price:4600, type:"Mensuelles", boxes:"6 lentilles", image:"https://d17sjz7j5l4n5m.cloudfront.net/products/d6db305e7ca593eda49d25e36908b353", description:"Technologie d’hydratation moderne pour les écrans et les longues journées." },
  { id:"acuvue", brand:"ACUVUE", name:"Acuvue Oasys", price:4500, type:"Bi-hebdomadaires", boxes:"6 lentilles", image:"https://d17sjz7j5l4n5m.cloudfront.net/products/f041ff8df8a98fc78e8cc9b4b617e792", description:"Confort haute performance et sensation de fraîcheur, même en environnement sec." },
  { id:"total30", brand:"ALCON", name:"Total30", price:5300, type:"Mensuelles", boxes:"6 lentilles", image:"https://d17sjz7j5l4n5m.cloudfront.net/products/c50858464f455a1c0909865285e1a6dc", description:"Une lentille premium pensée pour préserver une sensation de douceur durable." },
];
products.push(
  {id:"254",brand:"SOFLEX",name:"Soflex Toric",price:6250,type:"Annuelles",boxes:"1 lentille",image:"https://d17sjz7j5l4n5m.cloudfront.net/products/fba933388fbd69200bce8b4762f6490a",description:"Lentille torique annuelle."},
  {id:"253",brand:"SOFLEX",name:"Soflex",price:3200,type:"Annuelles",boxes:"1 lentille",image:"https://d17sjz7j5l4n5m.cloudfront.net/products/97f2975b62ee7eeb427b67a0c16bb3f9",description:"Lentille annuelle Soflex."},
  {id:"244",brand:"SOLEKO",name:"Soleko Toric",price:6650,type:"Annuelles",boxes:"1 lentille",image:"https://d17sjz7j5l4n5m.cloudfront.net/products/2aeba2bf44c4ef64b4c79c0b39541fb5",description:"Lentille torique annuelle Soleko."},
  {id:"230",brand:"SOLEKO",name:"Soleko Spheric",price:2800,type:"Annuelles",boxes:"1 lentille",image:"https://d17sjz7j5l4n5m.cloudfront.net/products/06542cc1f5af33ab6e16edc4615c0b0d",description:"Lentille spherique annuelle Soleko."},
  {id:"229",brand:"CORNELIA",name:"Cornelia Torique",price:8250,type:"Annuelles",boxes:"1 lentille",image:"https://d17sjz7j5l4n5m.cloudfront.net/products/f0f06d30527243c919d659ce89ab5c5c",description:"Lentille torique annuelle."},
  {id:"221",brand:"MENICON",name:"PremiO Toric",price:11200,type:"Bi-hebdomadaires",boxes:"6 lentilles",image:"https://d17sjz7j5l4n5m.cloudfront.net/products/161132e43d9f237e853ea283c151b9f8",description:"Lentilles toriques bi-hebdomadaires."},
  {id:"220",brand:"MENICON",name:"PremiO",price:7500,type:"Bi-hebdomadaires",boxes:"6 lentilles",image:"https://d17sjz7j5l4n5m.cloudfront.net/products/692bcf46b9f7cd303984f7842f3967bc",description:"Lentilles PremiO bi-hebdomadaires."},
  {id:"219",brand:"ACUVUE",name:"ACUVUE Oasys for Astigmatism",price:12000,type:"Bi-hebdomadaires",boxes:"6 lentilles",image:"https://d17sjz7j5l4n5m.cloudfront.net/products/076a36132dd4fd17cfc70d7ee264f2ec",description:"Lentilles pour astigmatisme."},
  {id:"218",brand:"ACUVUE",name:"ACUVUE Oasys",price:7950,type:"Bi-hebdomadaires",boxes:"6 lentilles",image:"https://d17sjz7j5l4n5m.cloudfront.net/products/054555510672fd58b962712a648a9425",description:"Lentilles Acuvue Oasys."},
  {id:"217",brand:"BAUSCH + LOMB",name:"PureVision 2",price:8400,type:"Mensuelles",boxes:"6 lentilles",image:"https://d17sjz7j5l4n5m.cloudfront.net/products/6017af783a3aa01efa641c6085abc9cf",description:"Lentilles mensuelles PureVision 2."},
  {id:"216",brand:"ALCON",name:"Air Optix plus Hydraglyde for Astigmatism",price:18700,type:"Mensuelles",boxes:"6 lentilles",image:"https://d17sjz7j5l4n5m.cloudfront.net/products/e754857601838a41e7db87981a4c07a5",description:"Lentilles Air Optix pour astigmatisme."},
  {id:"215",brand:"MENICON",name:"Miru Toric",price:16400,type:"Mensuelles",boxes:"6 lentilles",image:"https://d17sjz7j5l4n5m.cloudfront.net/products/21d81a3beab1994ca0dbdcfc84769650",description:"Lentilles toriques Miru."},
  {id:"214",brand:"MIRU",name:"Miru",price:9000,type:"Mensuelles",boxes:"6 lentilles",image:"https://d17sjz7j5l4n5m.cloudfront.net/products/e99caaf6c0665f2ca44602a23a5863f6",description:"Technologie MeniSilk pour une forte tenue en eau et une excellente transmissibilite a l'oxygene."},
  {id:"213",brand:"PROCLEAR",name:"Proclear toric XR",price:36200,type:"Mensuelles",boxes:"6 lentilles",image:"https://d17sjz7j5l4n5m.cloudfront.net/products/6f6e06b751cdcb25cce0f88106d0cba9",description:"Lentilles mensuelles toriques pour astigmatisme et secheresse oculaire."},
  {id:"212",brand:"PROCLEAR",name:"Proclear toric",price:14400,type:"Mensuelles",boxes:"6 lentilles",image:"https://d17sjz7j5l4n5m.cloudfront.net/products/7857d723407662c78e9f398e722f16c4",description:"Lentilles mensuelles toriques avec PC Technology pour le confort des yeux secs."},
);
const power = Array.from({length: 201}, (_, i) => (-25 + i * .25).toFixed(2).replace(".00", ".00"));
function money(value:number) { return new Intl.NumberFormat("fr-DZ").format(value) + " DA"; }

export default function App(){
 const [selected,setSelected]=useState<Product|null>(null); const [step,setStep]=useState(0); const [same,setSame]=useState<boolean|null>(null); const [method,setMethod]=useState<"manual"|"photo"|null>(null); const [qty,setQty]=useState(0); const [filter,setFilter]=useState("Toutes");
 const shown=useMemo(()=>filter==="Toutes"?products:products.filter(p=>p.type===filter),[filter]);
 const open=(p:Product)=>{setSelected(p);setStep(0);setSame(null);setMethod(null);setQty(0);window.scrollTo({top:0,behavior:"smooth"})};
 if(selected) return <main className="checkout"><header className="checkoutHead"><button onClick={()=>setSelected(null)} className="back">← Retour à la boutique</button><a className="logo">PRO <i>LENS</i></a><span>Commande sécurisée</span></header><section className="flow"><div className="progress"><span className={step>=0?"on":""}>1. Ordonnance</span><span className={step>=3?"on":""}>2. Quantité</span><span className={step>=4?"on":""}>3. Coordonnées</span></div><aside className="summary"><img src={selected.image} alt={selected.name}/><div><small>{selected.brand}</small><strong>{selected.name}</strong><em>{money(selected.price)} / boîte</em></div></aside>{step===0&&<div className="panel"><p className="eyebrow">ÉTAPE 1 / 3</p><h1>Avez-vous la même ordonnance dans les deux yeux&nbsp;?</h1><p>Nous adapterons votre sélection à votre correction.</p><div className="choice"><button onClick={()=>{setSame(true);setStep(1)}}>Oui <span>La même correction pour les deux yeux</span></button><button onClick={()=>{setSame(false);setStep(1)}}>Non <span>Une correction différente par œil</span></button></div></div>}{step===1&&<div className="panel"><p className="eyebrow">VOTRE ORDONNANCE</p><h1>Comment souhaitez-vous nous la transmettre&nbsp;?</h1><div className="choice"><button onClick={()=>{setMethod("manual");setStep(2)}}>Saisissez vos valeurs d’ordonnance <span>Entrez manuellement chaque valeur d’ordonnance.</span></button><button onClick={()=>setMethod("photo")} className={method==="photo"?"chosen":""}>Télécharger la photo <span>Une option facile si vous l’avez à portée de main.</span></button></div>{method==="photo"&&<><label className="upload">Déposez votre ordonnance ici<input type="file" accept="image/*,.pdf"/></label><button className="primary" onClick={()=>setStep(3)}>Suivant</button></>}</div>}{step===2&&<Prescription same={same===true} onNext={()=>setStep(3)}/>} {step===3&&<div className="panel"><p className="eyebrow">ÉTAPE 2 / 3</p><h1>Sélectionnez la quantité</h1><p>Chaque boîte contient {selected.boxes}.</p><div className="quantity"><button onClick={()=>setQty(Math.max(0,qty-1))}>−</button><strong>{qty}</strong><span>boîte{qty>1?"s":""}</span><button onClick={()=>setQty(qty+1)}>+</button></div><button disabled={!qty} className="primary" onClick={()=>setStep(4)}>Commander — {money(qty*selected.price)}</button></div>}{step===4&&<Order product={selected} qty={qty}/>}</section></main>
 return <main><header className="siteHead"><a className="logo">PRO <i>LENS</i></a><nav><a href="#catalogue">Lentilles</a><a href="#conseils">Nos conseils</a></nav><a className="call" href="tel:+213000000000">Besoin d’aide ?</a></header><section className="hero"><div><p className="eyebrow">VOTRE VISION, SANS COMPROMIS</p><h1>Les lentilles qui suivent votre regard.</h1><p className="lead">Une sélection experte de lentilles de contact, livrée avec simplicité. Retrouvez le confort que vos yeux méritent.</p><a className="primary" href="#catalogue">Découvrir les lentilles</a></div><div className="heroVisual"><div className="orb"/><img src="https://images.unsplash.com/photo-1559599101-f09722fb4948?auto=format&fit=crop&w=1000&q=85" alt="Femme portant des lentilles"/><span>Confort<br/><b>au quotidien</b></span></div></section><section className="trust"><span>✓ Produits certifiés</span><span>✦ Marques reconnues</span><span>⌁ Aide ordonnance</span><span>◌ Livraison en Algérie</span></section><section id="catalogue" className="catalog"><div className="sectionTop"><div><p className="eyebrow">LA SÉLECTION PRO LENS</p><h2>Trouvez vos lentilles.</h2></div><div className="filters">{["Toutes","Mensuelles","Bi-hebdomadaires"].map(x=><button className={filter===x?"active":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div></div><div className="grid">{shown.map(p=><article className="card" key={p.id}><div className="productImg"><img src={p.image} alt={p.name}/><span>{p.type}</span></div><div className="cardBody"><small>{p.brand}</small><h3>{p.name}</h3><p>{p.description}</p><div><strong>{money(p.price)}</strong><button onClick={()=>open(p)} className="neumorphic">Sélectionner</button></div></div></article>)}</div></section><section id="conseils" className="guide"><p className="eyebrow">UN ACHAT GUIDÉ</p><h2>Votre ordonnance, en toute simplicité.</h2><div><article><b>01</b><h3>Choisissez</h3><p>Sélectionnez les lentilles adaptées à votre usage.</p></article><article><b>02</b><h3>Indiquez</h3><p>Saisissez votre ordonnance ou transmettez-la en photo.</p></article><article><b>03</b><h3>Commandez</h3><p>Renseignez vos coordonnées pour finaliser votre demande.</p></article></div></section><footer><a className="logo">PRO <i>LENS</i></a><p>Voir net, vivre libre.</p><small>© 2026 Pro Lens. Tous droits réservés.</small></footer></main>
}
function Prescription({same,onNext}:{same:boolean;onNext:()=>void}){const fields=same?["OD — Œil droit"]:["OD — Œil droit","OG — Œil gauche"];return <div className="panel prescription"><p className="eyebrow">ÉTAPE 1 / 3</p><h1>Sélectionnez votre ordonnance</h1><p>Saisissez les valeurs indiquées par votre professionnel de santé.</p>{fields.map(x=><fieldset key={x}><legend>{x}</legend><label>Sphère ou Puissance (SPH/PWR/D)<select required><option value="">Sélectionner</option>{power.map(v=><option value={v} key={v}>{Number(v)>0?"+":""}{v}</option>)}</select></label><label>Courbe de base (BC)<select defaultValue="8.6"><option>8.4</option><option>8.6</option></select></label><label>Diamètre (DIA)<select defaultValue="14"><option>14</option><option>14.2</option><option>14.5</option></select></label></fieldset>)}<button className="primary" onClick={onNext}>Suivant</button></div>}
function Order({product,qty}:{product:Product;qty:number}){const [sent,setSent]=useState(false);return <div className="panel">{sent?<><p className="eyebrow">DEMANDE ENREGISTRÉE</p><h1>Merci, votre demande est prête.</h1><p>Nous vous recontacterons rapidement afin de confirmer votre commande de {qty} boîte{qty>1?"s":""} de {product.name}.</p></>:<><p className="eyebrow">ÉTAPE 3 / 3</p><h1>Vos coordonnées</h1><p>Nous vous recontacterons pour confirmer votre commande — aucun paiement n’est demandé en ligne.</p><form onSubmit={e=>{e.preventDefault();setSent(true)}}><label>Nom complet<input required placeholder="Votre nom"/></label><label>Téléphone<input required type="tel" placeholder="05 xx xx xx xx"/></label><label>Adresse de livraison<textarea required placeholder="Ville, wilaya, adresse complète"/></label><button className="primary">Envoyer ma demande</button></form></>}</div>}
